import {
  BLOCK_REGISTRY,
  ITEM_REGISTRY,
  PLACEABLE_BLOCK_IDS
} from "@/lib/voxelProtocol";
import { NOA_BLOCK_ENTRIES } from "@playground/voxel-content";

export const MC_TEX = {
  grassTop: "/minecraft-assets/block/grass_block_top.png",
  grassSide: "/minecraft-assets/block/grass_block_side.png",
  dirt: "/minecraft-assets/block/dirt.png",
  stone: "/minecraft-assets/block/stone.png",
  oakLog: "/minecraft-assets/block/oak_log.png",
  oakLogTop: "/minecraft-assets/block/oak_log_top.png",
  oakLeaves: "/minecraft-assets/block/oak_leaves.png",
  birchLog: "/minecraft-assets/block/birch_log.png",
  birchLogTop: "/minecraft-assets/block/birch_log_top.png",
  birchPlanks: "/minecraft-assets/block/birch_planks.png",
  birchLeaves: "/minecraft-assets/block/birch_leaves.png",
  spruceLog: "/minecraft-assets/block/spruce_log.png",
  spruceLogTop: "/minecraft-assets/block/spruce_log_top.png",
  sprucePlanks: "/minecraft-assets/block/spruce_planks.png",
  spruceLeaves: "/minecraft-assets/block/spruce_leaves.png",
  sand: "/minecraft-assets/block/sand.png",
  waterStill: "/minecraft-assets/block/water_still.png",
  glass: "/minecraft-assets/block/glass.png",
  cobblestone: "/minecraft-assets/block/cobblestone.png",
  oakPlanks: "/minecraft-assets/block/oak_planks.png",
  sapling: "/minecraft-assets/block/oak_sapling.png",
  gravel: "/minecraft-assets/block/gravel.png",
  goldOre: "/minecraft-assets/block/gold_ore.png",
  ironOre: "/minecraft-assets/block/iron_ore.png",
  coalOre: "/minecraft-assets/block/coal_ore.png",
  sponge: "/minecraft-assets/block/sponge.png",
  redWool: "/minecraft-assets/block/red_wool.png",
  orangeWool: "/minecraft-assets/block/orange_wool.png",
  yellowWool: "/minecraft-assets/block/yellow_wool.png",
  limeWool: "/minecraft-assets/block/lime_wool.png",
  greenWool: "/minecraft-assets/block/green_wool.png",
  cyanWool: "/minecraft-assets/block/cyan_wool.png",
  blueWool: "/minecraft-assets/block/blue_wool.png",
  purpleWool: "/minecraft-assets/block/purple_wool.png",
  magentaWool: "/minecraft-assets/block/magenta_wool.png",
  pinkWool: "/minecraft-assets/block/pink_wool.png",
  blackWool: "/minecraft-assets/block/black_wool.png",
  grayWool: "/minecraft-assets/block/gray_wool.png",
  whiteWool: "/minecraft-assets/block/white_wool.png",
  dandelion: "/minecraft-assets/block/dandelion.png",
  rose: "/minecraft-assets/block/red_flower.png",
  brownMushroom: "/minecraft-assets/block/brown_mushroom.png",
  redMushroom: "/minecraft-assets/block/red_mushroom.png",
  goldBlock: "/minecraft-assets/block/gold_block.png",
  ironBlock: "/minecraft-assets/block/iron_block.png",
  smoothStone: "/minecraft-assets/block/smooth_stone.png",
  smoothStoneSlabSide: "/minecraft-assets/block/smooth_stone_slab_side.png",
  bricks: "/minecraft-assets/block/bricks.png",
  tntTop: "/minecraft-assets/block/tnt_top.png",
  tntBottom: "/minecraft-assets/block/tnt_bottom.png",
  tntSide: "/minecraft-assets/block/tnt_side.png",
  bookshelf: "/minecraft-assets/block/bookshelf.png",
  mossyCobblestone: "/minecraft-assets/block/mossy_cobblestone.png",
  obsidian: "/minecraft-assets/block/obsidian.png",
  bedrock: "/minecraft-assets/block/bedrock.png",
  grassSnow: "/minecraft-assets/block/grass_snow.png",
  snow: "/minecraft-assets/block/snow.png",
  cactusTop: "/minecraft-assets/block/cactus_top.png",
  cactusBottom: "/minecraft-assets/block/cactus_bottom.png",
  cactusSide: "/minecraft-assets/block/cactus_side.png",
  deadBush: "/minecraft-assets/block/dead_bush.png",
  craftingTableTop: "/minecraft-assets/block/crafting_table_top.png",
  craftingTableSide: "/minecraft-assets/block/crafting_table_side.png",
  stoneBrick: "/minecraft-assets/block/stonebrick.png",
  brownWool: "/minecraft-assets/block/brown_wool.png",
  lightBlueWool: "/minecraft-assets/block/light_blue_wool.png",
  whiteStainedGlass: "/minecraft-assets/block/white_stained_glass.png",
  yellowStainedGlass: "/minecraft-assets/block/yellow_stained_glass.png",
  redStainedGlass: "/minecraft-assets/block/red_stained_glass.png",
  purpleStainedGlass: "/minecraft-assets/block/purple_stained_glass.png",
  pinkStainedGlass: "/minecraft-assets/block/pink_stained_glass.png",
  orangeStainedGlass: "/minecraft-assets/block/orange_stained_glass.png",
  magentaStainedGlass: "/minecraft-assets/block/magenta_stained_glass.png",
  limeStainedGlass: "/minecraft-assets/block/lime_stained_glass.png",
  lightBlueStainedGlass: "/minecraft-assets/block/light_blue_stained_glass.png",
  greenStainedGlass: "/minecraft-assets/block/green_stained_glass.png",
  grayStainedGlass: "/minecraft-assets/block/gray_stained_glass.png",
  cyanStainedGlass: "/minecraft-assets/block/cyan_stained_glass.png",
  brownStainedGlass: "/minecraft-assets/block/brown_stained_glass.png",
  blueStainedGlass: "/minecraft-assets/block/blue_stained_glass.png",
  blackStainedGlass: "/minecraft-assets/block/black_stained_glass.png",
  sandstone: "/minecraft-assets/block/sandstone.png",
  diamondOre: "/minecraft-assets/block/diamond_ore.png",
  diamondBlock: "/minecraft-assets/block/diamond_block.png",
  lapisOre: "/minecraft-assets/block/lapis_ore.png",
  lapisBlock: "/minecraft-assets/block/lapis_block.png",
  mossyStonebricks: "/minecraft-assets/block/mossy_stone_bricks.png",
  whiteConcrete: "/minecraft-assets/block/white_concrete.png",
  yellowConcrete: "/minecraft-assets/block/yellow_concrete.png",
  redConcrete: "/minecraft-assets/block/red_concrete.png",
  purpleConcrete: "/minecraft-assets/block/purple_concrete.png",
  pinkConcrete: "/minecraft-assets/block/pink_concrete.png",
  orangeConcrete: "/minecraft-assets/block/orange_concrete.png",
  magentaConcrete: "/minecraft-assets/block/magenta_concrete.png",
  limeConcrete: "/minecraft-assets/block/lime_concrete.png",
  lightBlueConcrete: "/minecraft-assets/block/light_blue_concrete.png",
  greenConcrete: "/minecraft-assets/block/green_concrete.png",
  grayConcrete: "/minecraft-assets/block/gray_concrete.png",
  cyanConcrete: "/minecraft-assets/block/cyan_concrete.png",
  brownConcrete: "/minecraft-assets/block/brown_concrete.png",
  blueConcrete: "/minecraft-assets/block/blue_concrete.png",
  blackConcrete: "/minecraft-assets/block/black_concrete.png",
  pumpkinTop: "/minecraft-assets/block/pumpkin_top.png",
  pumpkinSide: "/minecraft-assets/block/pumpkin_side.png",
  ice: "/minecraft-assets/block/ice.png",
  grassYellowTop: "/minecraft-assets/block/grass_yellow_top.png",
  grassYellowSide: "/minecraft-assets/block/grass_yellow_side.png",
  grassPlantYellow: "/minecraft-assets/block/grass_plant_yellow.png",
  leavesYellow: "/minecraft-assets/block/leaves_yellow.png",
  grassPlant: "/minecraft-assets/block/grass_plant.png",
  ladder: "/minecraft-assets/block/ladder.png",
  torch: "/minecraft-assets/block/torch.png",
  chest: "/minecraft-assets/block/chest.png",
  melonTop: "/minecraft-assets/block/melon_top.png",
  melonSide: "/minecraft-assets/block/melon_side.png",
  cakeTop: "/minecraft-assets/block/cake_top.png",
  cakeBottom: "/minecraft-assets/block/cake_bottom.png",
  cakeSide: "/minecraft-assets/block/cake_side.png",
  cakeInner: "/minecraft-assets/block/cake_inner.png",
  sugarCane: "/minecraft-assets/block/sugar_cane.png"
} as const;

export const BLOCK_HOTBAR_ICON: Record<number, string> = (() => {
  const m: Record<number, string> = {};
  for (const e of NOA_BLOCK_ENTRIES) {
    if (e.shape === "slabHalf") {
      m[e.id] = e.hotbarIconUrl;
    } else {
      m[e.id] = MC_TEX[e.hotbarTextureKey as keyof typeof MC_TEX];
    }
  }
  return m;
})();

export const BLOCK_HUD: Record<number, string> = {
  [BLOCK_REGISTRY.GRASS]: "דשא",
  [BLOCK_REGISTRY.DIRT]: "עפר",
  [BLOCK_REGISTRY.STONE]: "אבן",
  [BLOCK_REGISTRY.WOOD]: "עץ",
  [BLOCK_REGISTRY.LEAVES]: "עלים",
  [BLOCK_REGISTRY.SAND]: "חול",
  [BLOCK_REGISTRY.GLASS]: "זכוכית",
  [BLOCK_REGISTRY.COBBLESTONE]: "אבן מרוצפת",
  [BLOCK_REGISTRY.OAK_PLANKS]: "לוחות עץ",
  [BLOCK_REGISTRY.SAPLING]: "שתיל",
  [BLOCK_REGISTRY.GRAVEL]: "חצץ",
  [BLOCK_REGISTRY.GOLD_ORE]: "עפרת זהב",
  [BLOCK_REGISTRY.IRON_ORE]: "עפרת ברזל",
  [BLOCK_REGISTRY.COAL_ORE]: "עפרת פחם",
  [BLOCK_REGISTRY.SPONGE]: "ספוג",
  [BLOCK_REGISTRY.RED_WOOL]: "צמר אדום",
  [BLOCK_REGISTRY.ORANGE_WOOL]: "צמר כתום",
  [BLOCK_REGISTRY.YELLOW_WOOL]: "צמר צהוב",
  [BLOCK_REGISTRY.LIME_WOOL]: "צמר ליים",
  [BLOCK_REGISTRY.GREEN_WOOL]: "צמר ירוק",
  [BLOCK_REGISTRY.CYAN_WOOL]: "צמר טורקיז",
  [BLOCK_REGISTRY.BLUE_WOOL]: "צמר כחול",
  [BLOCK_REGISTRY.PURPLE_WOOL]: "צמר סגול",
  [BLOCK_REGISTRY.MAGENTA_WOOL]: "צמר מג'נטה",
  [BLOCK_REGISTRY.PINK_WOOL]: "צמר ורוד",
  [BLOCK_REGISTRY.BLACK_WOOL]: "צמר שחור",
  [BLOCK_REGISTRY.GRAY_WOOL]: "צמר אפור",
  [BLOCK_REGISTRY.WHITE_WOOL]: "צמר לבן",
  [BLOCK_REGISTRY.DANDELION]: "שן הארי",
  [BLOCK_REGISTRY.ROSE]: "ורד",
  [BLOCK_REGISTRY.BROWN_MUSHROOM]: "פטרייה חומה",
  [BLOCK_REGISTRY.RED_MUSHROOM]: "פטרייה אדומה",
  [BLOCK_REGISTRY.GOLD_BLOCK]: "בלוק זהב",
  [BLOCK_REGISTRY.IRON_BLOCK]: "בלוק ברזל",
  [BLOCK_REGISTRY.STONE_SLAB]: "לוח אבן",
  [BLOCK_REGISTRY.BRICKS]: "לבנים",
  [BLOCK_REGISTRY.TNT]: "TNT",
  [BLOCK_REGISTRY.BOOKSHELF]: "ספרייה",
  [BLOCK_REGISTRY.MOSSY_COBBLESTONE]: "אבן טחובה",
  [BLOCK_REGISTRY.OBSIDIAN]: "אובסידיאן",
  [BLOCK_REGISTRY.BEDROCK]: "סלע יסוד",
  [BLOCK_REGISTRY.BIRCH_LOG]: "עץ ליבנה",
  [BLOCK_REGISTRY.BIRCH_PLANKS]: "לוחות ליבנה",
  [BLOCK_REGISTRY.BIRCH_LEAVES]: "עלי ליבנה",
  [BLOCK_REGISTRY.SPRUCE_LOG]: "עץ אשוח",
  [BLOCK_REGISTRY.SPRUCE_PLANKS]: "לוחות אשוח",
  [BLOCK_REGISTRY.SPRUCE_LEAVES]: "עלי אשוח",
  [BLOCK_REGISTRY.GRASS_SNOW]: "דשא מושלג",
  [BLOCK_REGISTRY.BARRIER]: "מחסום",
  [BLOCK_REGISTRY.SNOW]: "שלג",
  [BLOCK_REGISTRY.CACTUS]: "קקטוס",
  [BLOCK_REGISTRY.DEADBUSH]: "שיח יבש",
  [BLOCK_REGISTRY.CRAFTING]: "שולחן יצירה",
  [BLOCK_REGISTRY.STONEBRICK]: "לבני אבן",
  [BLOCK_REGISTRY.BROWN_WOOL]: "צמר חום",
  [BLOCK_REGISTRY.LIGHT_BLUE_WOOL]: "צמר תכלת",
  [BLOCK_REGISTRY.WHITE_STAINED_GLASS]: "זכוכית לבנה",
  [BLOCK_REGISTRY.YELLOW_STAINED_GLASS]: "זכוכית צהובה",
  [BLOCK_REGISTRY.RED_STAINED_GLASS]: "זכוכית אדומה",
  [BLOCK_REGISTRY.PURPLE_STAINED_GLASS]: "זכוכית סגולה",
  [BLOCK_REGISTRY.PINK_STAINED_GLASS]: "זכוכית ורודה",
  [BLOCK_REGISTRY.ORANGE_STAINED_GLASS]: "זכוכית כתומה",
  [BLOCK_REGISTRY.MAGENTA_STAINED_GLASS]: "זכוכית מג'נטה",
  [BLOCK_REGISTRY.LIME_STAINED_GLASS]: "זכוכית ליים",
  [BLOCK_REGISTRY.LIGHT_BLUE_STAINED_GLASS]: "זכוכית תכלת",
  [BLOCK_REGISTRY.GREEN_STAINED_GLASS]: "זכוכית ירוקה",
  [BLOCK_REGISTRY.GRAY_STAINED_GLASS]: "זכוכית אפורה",
  [BLOCK_REGISTRY.CYAN_STAINED_GLASS]: "זכוכית טורקיז",
  [BLOCK_REGISTRY.BROWN_STAINED_GLASS]: "זכוכית חומה",
  [BLOCK_REGISTRY.BLUE_STAINED_GLASS]: "זכוכית כחולה",
  [BLOCK_REGISTRY.BLACK_STAINED_GLASS]: "זכוכית שחורה",
  [BLOCK_REGISTRY.SANDSTONE]: "אבן חול",
  [BLOCK_REGISTRY.DIAMOND_ORE]: "עפרת יהלום",
  [BLOCK_REGISTRY.DIAMOND_BLOCK]: "בלוק יהלום",
  [BLOCK_REGISTRY.LAPIS_ORE]: "עפרת לפיס",
  [BLOCK_REGISTRY.LAPIS_BLOCK]: "בלוק לפיס",
  [BLOCK_REGISTRY.MOSSY_STONEBRICKS]: "לבני אבן טחובות",
  [BLOCK_REGISTRY.WHITE_CONCRETE]: "בטון לבן",
  [BLOCK_REGISTRY.YELLOW_CONCRETE]: "בטון צהוב",
  [BLOCK_REGISTRY.RED_CONCRETE]: "בטון אדום",
  [BLOCK_REGISTRY.PURPLE_CONCRETE]: "בטון סגול",
  [BLOCK_REGISTRY.PINK_CONCRETE]: "בטון ורוד",
  [BLOCK_REGISTRY.ORANGE_CONCRETE]: "בטון כתום",
  [BLOCK_REGISTRY.MAGENTA_CONCRETE]: "בטון מג'נטה",
  [BLOCK_REGISTRY.LIME_CONCRETE]: "בטון ליים",
  [BLOCK_REGISTRY.LIGHT_BLUE_CONCRETE]: "בטון תכלת",
  [BLOCK_REGISTRY.GREEN_CONCRETE]: "בטון ירוק",
  [BLOCK_REGISTRY.GRAY_CONCRETE]: "בטון אפור",
  [BLOCK_REGISTRY.CYAN_CONCRETE]: "בטון טורקיז",
  [BLOCK_REGISTRY.BROWN_CONCRETE]: "בטון חום",
  [BLOCK_REGISTRY.BLUE_CONCRETE]: "בטון כחול",
  [BLOCK_REGISTRY.BLACK_CONCRETE]: "בטון שחור",
  [BLOCK_REGISTRY.PUMPKIN]: "דלעת",
  [BLOCK_REGISTRY.ICE]: "קרח",
  [BLOCK_REGISTRY.GRASS_YELLOW]: "דשא יבש",
  [BLOCK_REGISTRY.GRASS_PLANT_YELLOW]: "עשב יבש",
  [BLOCK_REGISTRY.LEAVES_YELLOW]: "עלים צהובים",
  [BLOCK_REGISTRY.GRASS_PLANT]: "עשב",
  [BLOCK_REGISTRY.LADDER]: "סולם",
  [BLOCK_REGISTRY.TORCH]: "לפיד",
  [BLOCK_REGISTRY.CHEST]: "תיבה",
  [BLOCK_REGISTRY.MELON]: "אבטיח",
  [BLOCK_REGISTRY.CAKE]: "עוגה",
  [BLOCK_REGISTRY.CAKE_5]: "עוגה (5 פרוסות)",
  [BLOCK_REGISTRY.CAKE_4]: "עוגה (4 פרוסות)",
  [BLOCK_REGISTRY.CAKE_3]: "עוגה (3 פרוסות)",
  [BLOCK_REGISTRY.CAKE_2]: "עוגה (2 פרוסות)",
  [BLOCK_REGISTRY.CAKE_1]: "עוגה (פרוסה אחת)",
  [BLOCK_REGISTRY.SUGAR_CANE]: "קני סוכר"
};

export const ITEM_HUD: Record<number, string> = {
  [ITEM_REGISTRY.STICK]: "מקל",
  [ITEM_REGISTRY.PLANKS]: "לוחות",
  [ITEM_REGISTRY.WOODEN_PICKAXE]: "מכוש עץ",
  [ITEM_REGISTRY.STONE_PICKAXE]: "מכוש אבן",
  [ITEM_REGISTRY.IRON_PICKAXE]: "מכוש ברזל",
  [ITEM_REGISTRY.DIAMOND_PICKAXE]: "מכוש יהלום",
  [ITEM_REGISTRY.WOODEN_AXE]: "גרזן עץ",
  [ITEM_REGISTRY.STONE_AXE]: "גרזן אבן",
  [ITEM_REGISTRY.IRON_AXE]: "גרזן ברזל",
  [ITEM_REGISTRY.WOODEN_SHOVEL]: "את עץ",
  [ITEM_REGISTRY.STONE_SHOVEL]: "את אבן",
  [ITEM_REGISTRY.DIAMOND_AXE]: "גרזן יהלום",
  [ITEM_REGISTRY.SWIFT_PICKAXE]: "מכוש מהיר",
  [ITEM_REGISTRY.BUCKET]: "דלי",
  [ITEM_REGISTRY.WATER_BUCKET]: "דלי מים",
  [ITEM_REGISTRY.IRON_INGOT]: "מטיל ברזל",
  [ITEM_REGISTRY.GOLD_INGOT]: "מטיל זהב",
  [ITEM_REGISTRY.DIAMOND]: "יהלום",
  [ITEM_REGISTRY.COAL]: "פחם",
  [ITEM_REGISTRY.FLINT]: "צור",
  [ITEM_REGISTRY.WHEAT]: "חיטה",
  [ITEM_REGISTRY.BREAD]: "לחם",
  [ITEM_REGISTRY.APPLE]: "תפוח",
  [ITEM_REGISTRY.FLINT_AND_STEEL]: "מצית צור וברזל",
  [ITEM_REGISTRY.HEAVY_SHIELD]: "מגן כבד",
  [ITEM_REGISTRY.FEATHER_FALLING_TALISMAN]: "קמע נפילת נוצה",
  [ITEM_REGISTRY.HELIOS_MEDALLION]: "מדליון הליוס",
  [ITEM_REGISTRY.HELIUM_BOOTS]: "מגפי הליום",
  [ITEM_REGISTRY.GLOW_TALISMAN]: "קמע זוהר",
  [ITEM_REGISTRY.SUGAR]: "סוכר",
  [ITEM_REGISTRY.COCOA_BEANS]: "פולי קקאו",
  [ITEM_REGISTRY.EGG]: "ביצה",
  [ITEM_REGISTRY.RAW_MEAT]: "בשר נא",
  [ITEM_REGISTRY.COOKED_MEAT]: "בשר מבושל",
  [ITEM_REGISTRY.RAW_BEEF]: "בשר בקר נא",
  [ITEM_REGISTRY.COOKED_BEEF]: "סטייק",
  [ITEM_REGISTRY.COOKIE]: "עוגייה",
  [ITEM_REGISTRY.MELON_SLICE]: "פלח אבטיח",
  [ITEM_REGISTRY.CARROT]: "גזר",
  [ITEM_REGISTRY.GOLDEN_CARROT]: "גזר זהב",
  [ITEM_REGISTRY.POTATO]: "תפוח אדמה",
  [ITEM_REGISTRY.BAKED_POTATO]: "תפוח אדמה אפוי",
  [ITEM_REGISTRY.POISONOUS_POTATO]: "תפוח אדמה רעיל",
  [ITEM_REGISTRY.GUNPOWDER]: "אבק שרפה"
};

const HOTBAR = PLACEABLE_BLOCK_IDS;

export function visibleCreativeHotbarBlocks(selectedBlockId: number): number[] {
  const blocks = HOTBAR.slice(0, 9);
  if (!blocks.includes(selectedBlockId) && PLACEABLE_BLOCK_IDS.includes(selectedBlockId)) {
    blocks[8] = selectedBlockId;
  }
  return blocks;
}
